pretrain_mlp_config_xs = {
    'mlp_size': 'XS',
    'modelstate_size': 256,
    'dynamic_model': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'organ_dynamic_model': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'compound_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 0, 'cmax': 0.},
    'train_mode': 'schedule',
    'train_seq_len': 50,
    'valid_seq_len': 50,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 100,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 1000,
    'update_obs': True,
    'update_organ': True,
    'update_list': None
}