# ----------------------------------------- Pretrain Config -----------------------------------------
pretrain_rnn_config_xs = {
    'rnn_size': 'XS',
    'modelstate_size': 256,
    'dynamic_model': {'hidden_dim': 512, 'rnn_num_layers': 4, 'layer_norm': True},
    'organ_dynamic_model': {'hidden_dim': 256, 'rnn_num_layers': 1, 'layer_norm': True},
    'compound_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 0, 'cmax': 0.},
    'train_mode': 'schedule',
    'train_seq_len': 50,
    'valid_seq_len': 50,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 100,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 1000,
    'update_obs': True,
    'update_organ': True,
    'update_list': None
}


pretrain_rnn_config_s = {
    'rnn_size': 'S',
    'modelstate_size': 512,
    'dynamic_model': {'hidden_dim': 512, 'rnn_num_layers': 4, 'layer_norm': True},
    'organ_dynamic_model': {'hidden_dim': 512, 'rnn_num_layers': 2, 'layer_norm': True},
    'compound_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 0, 'cmax': 0.},
    'train_mode': 'schedule',
    'train_seq_len': 50,
    'valid_seq_len': 50,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 100,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 100,
    'update_obs': True,
    'update_organ': True,
    'update_list': None
}

pretrain_rnn_config_m = {
    'rnn_size': 'M',
    'modelstate_size': 768,
    'dynamic_model': {'hidden_dim': 768, 'rnn_num_layers': 4, 'layer_norm': True},
    'organ_dynamic_model': {'hidden_dim': 768, 'rnn_num_layers': 2, 'layer_norm': True},
    'compound_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 0, 'cmax': 0.},
    'train_mode': 'schedule',
    'train_seq_len': 50,
    'valid_seq_len': 50,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 100,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 100,
    'update_obs': True,
    'update_organ': True,
    'update_list': None
}


# ----------------------------------------- Finetune Config -----------------------------------------
finetune_rnn_config_xs = {
    'rnn_size': 'XS',
    'modelstate_size': 256,
    'dynamic_model': {'hidden_dim': 512, 'rnn_num_layers': 4, 'layer_norm': True},
    'organ_dynamic_model': {'hidden_dim': 256, 'rnn_num_layers': 1, 'layer_norm': True},
    'compound_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 1.0, 'cmax': 0.},
    'train_mode': 'schedule',
    'train_seq_len': -1,
    'valid_seq_len': -1,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 10,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 10,
    'update_obs': True,
    'update_organ': False,
    'update_list': ["DynamicModel"]
}


finetune_rnn_config_s = {
    'rnn_size': 'S',
    'modelstate_size': 512,
    'dynamic_model': {'hidden_dim': 512, 'rnn_num_layers': 4, 'layer_norm': True},
    'organ_dynamic_model': {'hidden_dim': 512, 'rnn_num_layers': 2, 'layer_norm': True},
    'compound_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 2, 'dist': None, 'node_size': 512, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 1.0, 'cmax': 0},
    'train_mode': 'schedule',
    'train_seq_len': -1,
    'valid_seq_len': -1,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 100,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 100,
    'update_obs': True,
    'update_organ': False,
    'update_list': ["DynamicModel", "PopulationEncoder"]
}

finetune_rnn_config_m = {
    'rnn_size': 'M',
    'modelstate_size': 768,
    'dynamic_model': {'hidden_dim': 768, 'rnn_num_layers': 4, 'layer_norm': True},
    'organ_dynamic_model': {'hidden_dim': 768, 'rnn_num_layers': 2, 'layer_norm': True},
    'compound_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 3, 'dist': None, 'node_size': 768, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 1.0, 'auc': 0., 'cmax': 1.0},
    'train_mode': 'schedule',
    'train_seq_len': -1,
    'valid_seq_len': -1,
    'grad_clip_norm': 1000,
    'model_lr': 1e-4,
    'log_interval': 100,
    'save_interval': 10,
    'plot_interval': 10,
    'batch_size': 512,
    'train_epochs': 100,
    'update_obs': True,
    'update_organ': False,
    'update_list': ["DynamicModel", "PopulationEncoder"]
}