trf_config_xs = {
    'trf_size': 'XS',
    'modelstate_size': 256,
    'compound_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'population_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'action_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'obs_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_encoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'organ_decoder': {'activation': 'silu', 'layers': 1, 'dist': None, 'node_size': 256, 'dropout': 0.1},
    'loss_scale': {'reconstruction': 1.0, 'consistency': 0.},
    'seq_len': 50,
    'grad_clip_norm': 1000,
    'model_lr': 3e-4,
    'batch_size': 32,
    'train_epochs': 300,
    'update_obs': True,
    'update_organ': True,
    # 'update_list': ['OrganEncoder', 'OrganDecoder', 'OrganDynamicModel'],
    'update_list': None,
    'dynamic_model': {
        'hidden_dim': 256, 
        'layer_norm': True,
        'n_embd': 1024,
        'n_layer': 2,
        'n_head': 1,
        },
    'organ_dynamic_model': {
        'hidden_dim': 256,
        'layer_norm': True,
        'n_embd': 1024,
        'n_layer': 2,
        'n_head': 1,
        }
}
